medprint/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("medprint.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # path("design/", include("design.urls")),
    # path("order/", include("order.urls")),
    path("library/", include("library.urls")),
    # path("user_types/", include("user_types.urls")),
    path("location_test/", include("location_test.urls")),
    path("profile/", include("profiles.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

medprint/user_types/urls.py
from django.urls import include, path
from .views import *

app_name = 'user_types'

urlpatterns = [
    # path("base/create/", BaseModelCreate.as_view(), name="new"),
    # path("base/<int:pk>/", BaseModelDetail.as_view(), name="detail"),
    path("makers/new/", MakerCreate.as_view(), name="maker_new"),
    path("makers/<int:pk>/", MakerDetail.as_view(), name="maker_detail"),
    path("makers/", MakerList.as_view(), name="maker_list"),
    path("hospitals/new/", HospitalCreate.as_view(), name="hospital_new"),
    path("hospitals/<int:pk>/", HospitalDetail.as_view(), name="hospital_detail"),
    path("hospitals/", HospitalList.as_view(), name="hospital_list"),
    path("deliverers/new/", DelivererCreate.as_view(), name="deliverer_new"),
    path("deliverers/<int:pk>/", DelivererDetail.as_view(), name="deliverer_detail"),
    path("deliverers/", DelivererList.as_view(), name="deliverer_list"),
    path("dispatchers/new/", DispatcherCreate.as_view(), name="dispatcher_new"),
    path("dispatchers/<int:pk>/", DispatcherDetail.as_view(), name="dispatcher_detail"),
    path("dispatchers/", DispatcherList.as_view(), name="dispatcher_list"),
]

medprint/user_types/models.py
import json
from django.db import models
from location_field.models.plain import PlainLocationField
from phone_field import PhoneField
from config.settings.base import AUTH_USER_MODEL
from django import forms
from datetime import datetime
from django.contrib.postgres.fields import JSONField

user_types = (
    ('hospital', 'Hospital'),
    ('maker', 'Maker'),
    ('deliverer', 'Deliverer'),
)


# class BaseModel(models.Model):
# name = models.CharField(max_length=250)
# user_type = models.CharField(choices=user_types, null=True, default="hospital", max_length=20)
# phone = PhoneField(null=True, blank=True)
# email = models.EmailField(max_length=100, null=True, blank=True)
# url = models.URLField(max_length=200, blank=True)
# user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
# related_name="user_types", null=True, blank=True)

# address_search = models.CharField(
# max_length=250, help_text="Start typing your address or name of your business, and stop when it shows up on the map. We'll reverse engineer your address from there")
# location = PlainLocationField(based_fields=['address_search'], zoom=7, null=True, blank=True)

# address_data = models.CharField(max_length=500, default='', null=True, blank=True)

# def __str__(self):
# return self.name


class CommonUser(models.Model):
    name = models.CharField(max_length=250)
    phone = PhoneField(null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    url = models.URLField(max_length=200, blank=True)

    address_search = models.CharField(
        max_length=250, help_text="Start typing your address or name of your business, and stop when it shows up on the map. We'll reverse engineer your address from there")
    location = PlainLocationField(based_fields=['address_search'], zoom=7, null=True, blank=True)
    address_json = JSONField(blank=True, null=True, default=dict)

    user_notes = models.TextField(blank=True, null=True)  # Notes the user makes
    staff_notes = models.TextField(blank=True, null=True)  # Notes staff can make about user

    status_verified = models.BooleanField(default=False, blank=True, null=True)
    status_active = models.BooleanField(default=True, blank=True, null=True)

    timestamp_create = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    timestamp_update = models.DateTimeField(auto_now=True, null=True, blank=True)

    @property
    def address_detail(self):
        data = json.loads(self.address_json)
        return data

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Maker(CommonUser):

    equipment_choices = (
        ('3d_printer', '3D printer'),
        ('laser_cutter', 'Laser cutter'),
    )
    equipment = models.CharField(choices=equipment_choices, max_length=250, null=True, blank=True)

    equipment_list = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=equipment_choices)

    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="profile_maker", null=True, blank=True)


class Hospital(CommonUser):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="profile_hospital", null=True, blank=True)


class Dispatcher(CommonUser):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="profile_dispatcher", null=True, blank=True)


class Deliverer(CommonUser):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="profile_deliverer", null=True, blank=True)
    delivery_vehicle = models.TextField(blank=True, null=True)  # Vehicle info - how much can they carry, etc?
    delivery_area = models.TextField(blank=True, null=True)

medprint/user_types/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class CommonCreateForm(ModelForm):

    class Meta:
        model = ''
        exclude = []


class BaseModelCreateForm(ModelForm):

    class Meta:
        model = Maker
        exclude = []


class MakerCreateForm(CommonCreateForm):

    class Meta(CommonCreateForm.Meta):
        model = Maker


class HospitalCreateForm(CommonCreateForm):

    class Meta(CommonCreateForm.Meta):
        model = Hospital


class DelivererCreateForm(CommonCreateForm):

    class Meta(CommonCreateForm.Meta):
        model = Deliverer


class DispatcherCreateForm(CommonCreateForm):

    class Meta(CommonCreateForm.Meta):
        model = Dispatcher

medprint/user_types/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from .models import *
from .forms import *
from geopy.geocoders import Nominatim
from django.contrib import messages

geolocator = Nominatim(user_agent="django_frontend")


class CommonCreate(CreateView):
    model = ''
    template_name = 'base/create.html'
    form = BaseModelCreateForm
    fields = [
        'name',
        'address_search',
        'location',
        'email',
        'phone',
        'url',
        'user_notes'
    ]
    success_url = "/"

    def post(self, request, *args, **kwargs):
        form_data = self.form(request.POST)
        new_model = form_data.save(commit=False)
        address_data = geolocator.reverse(new_model.location, addressdetails=True)
        address_json = json.dumps(address_data.raw)
        new_model.address_json = address_json
        new_model.user = self.request.user
        new_model.save()
        redirect_url = '/user_types/' + self.url_string + '/'+str(new_model.pk)
        return HttpResponseRedirect(redirect_url)


class MakerCreate(CommonCreate):
    form = MakerCreateForm
    model = Maker
    fields = [
        'name',
        'address_search',
        'location',
        'email',
        'phone',
        'url',
        'address_json',
    ]
    fields.append('equipment')
    url_string = 'makers'


class HospitalCreate(CommonCreate):
    form = HospitalCreateForm
    model = Hospital
    url_string = 'hospitals'


class DelivererCreate(CommonCreate):
    form = DelivererCreateForm
    model = Deliverer
    url_string = 'deliverers'


class DispatcherCreate(CommonCreate):
    form = DispatcherCreateForm
    model = Dispatcher
    url_string = 'dispatchers'


class CommonDetail(DetailView):
    template_name = "base/detail.html"


class MakerDetail(CommonDetail):
    model = Maker


class HospitalDetail(CommonDetail):
    model = Hospital


class DelivererDetail(CommonDetail):
    model = Deliverer


class DispatcherDetail(CommonDetail):
    model = Dispatcher


class CommonList(ListView):
    paginate_by = 10


class MakerList(CommonList):
    template_name = "lists/list_makers.html"
    model = Maker


class HospitalList(CommonList):
    template_name = "lists/list_hospitals.html"
    model = Hospital


class DelivererList(CommonList):
    template_name = "lists/list_deliverers.html"
    model = Deliverer


class DispatcherList(CommonList):
    template_name = "lists/list_dispatchers.html"
    model = Dispatcher

medprint/user_types/templates/lists/list_deliverers.html
{% extends 'base.html' %}
{% load markdown %}
{% load static %}

{% block title %}
Deliverers
{% endblock title %}


{% block content %}
<div class="title-buttons">
    <div class="row">
        <div class="col-sm-10 col-12">
            <h1>Deliverers</h1>
        </div>
        <div class="col-sm-2 col-12">
            <a href="new" class="btn btn-primary mt-4 mb-4">Create new</a>
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
        </tr>
    </thead>
{% for object in object_list %}
<tr>
    <th>
        <a href="{% url "user_types:hospital_detail" pk=object.pk %}">
            {{object.name}}
        </a>
    </th>
    <td>{{object.address_detail.address.suburb}}, {{object.address_detail.address.city}}, {{object.address_detail.address.country}}</td>
</tr>

{% empty %}
Nothing to list!
{% endfor %}
</table>

{% endblock content %}

medprint/user_types/templates/lists/list_dispatchers.html
{% extends 'base.html' %}
{% load markdown %}
{% load static %}

{% block title %}
Dispatchers
{% endblock title %}


{% block content %}
<div class="title-buttons">
    <div class="row">
        <div class="col-sm-10 col-12">
            <h1>Dispatchers</h1>
        </div>
        <div class="col-sm-2 col-12">
            <a href="new" class="btn btn-primary mt-4 mb-4">Create new</a>
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
        </tr>
    </thead>
{% for object in object_list %}
<tr>
    <th>
        <a href="{% url "user_types:hospital_detail" pk=object.pk %}">
            {{object.name}}
        </a>
    </th>
    <td>{{object.address_detail.address.suburb}}, {{object.address_detail.address.city}}, {{object.address_detail.address.country}}</td>
</tr>

{% empty %}
Nothing to list!
{% endfor %}
</table>

{% endblock content %}

medprint/user_types/templates/lists/list_hospitals.html
{% extends 'base.html' %}
{% load markdown %}
{% load static %}
{% load object_list %}

{% block title %}
Hospitals
{% endblock title %}


{% block content %}
<div class="title-buttons">
    <div class="row">
        <div class="col-sm-10 col-12">
            <h1>Hospitals</h1>
        </div>
        <div class="col-sm-2 col-12">
            <a href="new" class="btn btn-primary mt-4 mb-4">Create new</a>
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
        </tr>
    </thead>
{% for object in object_list %}
<tr>
    <th>
        <a href="{% url "user_types:hospital_detail" pk=object.pk %}">
            {{object.name}}
        </a>
    </th>
    <td>{{object.address_detail.address.suburb}}, {{object.address_detail.address.city}}, {{object.address_detail.address.country}}</td>
</tr>

{% empty %}
Nothing to list!
{% endfor %}
</table>

{% endblock content %}

medprint/user_types/templates/lists/list_makers.html
{% extends 'base.html' %}
{% load markdown %}
{% load static %}

{% block title %}
Makers
{% endblock title %}


{% block content %}
<div class="title-buttons">
    <div class="row">
        <div class="col-sm-10 col-12">
            <h1>Makers</h1>
        </div>
        <div class="col-sm-2 col-12">
            <a href="new" class="btn btn-primary mt-4 mb-4">Create new</a>
            {% if request.user == object.user %}
            <a href="edit" class="btn btn-outline-primary">Edit</a>
            <a href="delete" class="btn btn-outline-danger">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Equipment</th>
        </tr>
    </thead>
{% for object in object_list %}
<tr>
    <th>
        <a href="{% url "user_types:maker_detail" pk=object.pk %}">
            {{object.name}}
        </a>
    </th>
    <td>{{object.address_detail.address.suburb}}, {{object.address_detail.address.city}}, {{object.address_detail.address.country}}</td>
    <td>{{object.equipment}}</td>
</tr>

{% empty %}
Nothing to list!
{% endfor %}
</table>

{% endblock content %}